import wpRedirects from '../content/wp-redirects.json';

/** Old WordPress paths → new paths. Generated by scripts/wordpress/import.mjs. */
const WP: Record<string, string> = wpRedirects;

/** Where an old WordPress address should go now, or null. */
export function legacyRedirect(pathname: string): string | null {
  let p: string;
  try {
    p = decodeURIComponent(pathname).toLowerCase().replace(/\/+$/, '') || '/';
  } catch {
    return null;
  }
  if (WP[p]) return WP[p]!;
  if (/^\/(category|tag|author)\/./.test(p) || /^\/\d{4}(\/\d{2}){0,2}$/.test(p) || p === '/page' || /^\/page\/\d+$/.test(p)) return '/notes';
  if (/^\/[a-z0-9-]+\/(feed|amp)$/.test(p)) {
    const base = WP[p.replace(/\/(feed|amp)$/, '')];
    if (base) return base;
  }
  return null;
}
